server:
  port: 8082
spring:
  application:
    name: consumer # 应用名称
eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找

feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能

management:
  server:
    port: 8023
  endpoints:
    web:
      exposure:
        include: hystrix.stream